version: "3.8"
services:
  calculadora:
    image: node:18-alpine
    container_name: frontapp
    entrypoint: /bin/sh
    command: -c "yarn && yarn run dev"
    ports:
      - 8080:8080
    working_dir: /srv/app
    volumes:
      - .:/srv/app
    tty: true

    