version: "3.8"
services:
  calculadora:
    image: kpisoluciones/calculadoraigtf
    container_name: frontapp
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /srv/app
    volumes:
      - .:/srv/app
    tty: true
    