version: "3.8"
services:
  calculadora:
    image: node:alpine
    container_name: frontapp
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
    